from pathlib import Path

path = Path("app/src/main/java/com/mixtervee/fastmagnifier/ScreenMagnifierService.kt")
text = path.read_text(encoding="utf-8")

old = '''    private fun dispatchMappedTap(screenX: Float, screenY: Float) {\n        val lens = lensView\n        val params = lensParams\n        val originalFlags = params?.flags\n\n        if (lens != null && params != null && originalFlags != null) {\n            params.flags = originalFlags or WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE\n            runCatching { windowManager.updateViewLayout(lens, params) }\n        }\n\n        val path = Path().apply { moveTo(screenX, screenY) }\n        val gesture = GestureDescription.Builder()\n            .addStroke(GestureDescription.StrokeDescription(path, 0L, 60L))\n            .build()\n\n        val restoreOverlay = {\n            if (lens != null && params != null && originalFlags != null && lens.isAttachedToWindow) {\n                params.flags = originalFlags\n                runCatching { windowManager.updateViewLayout(lens, params) }\n            }\n            mainHandler.postDelayed({ requestImmediateRefresh() }, 120L)\n        }\n\n        val dispatched = dispatchGesture(\n            gesture,\n            object : GestureResultCallback() {\n                override fun onCompleted(gestureDescription: GestureDescription?) {\n                    restoreOverlay()\n                }\n\n                override fun onCancelled(gestureDescription: GestureDescription?) {\n                    restoreOverlay()\n                }\n            },\n            mainHandler\n        )\n\n        if (!dispatched) restoreOverlay()\n    }'''

new = '''    private fun dispatchMappedTap(screenX: Float, screenY: Float) {\n        val lens = lensView ?: return\n        val params = lensParams ?: return\n        var restored = false\n\n        fun restoreOverlay() {\n            if (restored) return\n            restored = true\n            if (magnifierRunning && !lens.isAttachedToWindow) {\n                runCatching { windowManager.addView(lens, params) }\n            }\n            mainHandler.postDelayed({ requestImmediateRefresh() }, 120L)\n        }\n\n        // Remove the overlay for the synthetic tap instead of making the whole\n        // overlay NOT_TOUCHABLE. Some Android builds can leave that flag stuck,\n        // which disables Back/Exit until the service is restarted.\n        if (lens.isAttachedToWindow) {\n            runCatching { windowManager.removeViewImmediate(lens) }\n        }\n\n        val tapPath = Path().apply { moveTo(screenX, screenY) }\n        val gesture = GestureDescription.Builder()\n            .addStroke(GestureDescription.StrokeDescription(tapPath, 0L, 70L))\n            .build()\n\n        // Give the underlying app one frame to become touchable after the overlay\n        // is removed, then send the mapped tap. A watchdog always restores the lens\n        // even if an OEM fails to deliver a gesture callback.\n        mainHandler.postDelayed({\n            if (!magnifierRunning) {\n                restoreOverlay()\n                return@postDelayed\n            }\n\n            val dispatched = dispatchGesture(\n                gesture,\n                object : GestureResultCallback() {\n                    override fun onCompleted(gestureDescription: GestureDescription?) {\n                        restoreOverlay()\n                    }\n\n                    override fun onCancelled(gestureDescription: GestureDescription?) {\n                        restoreOverlay()\n                    }\n                },\n                mainHandler\n            )\n\n            if (!dispatched) restoreOverlay()\n        }, 50L)\n\n        mainHandler.postDelayed({ restoreOverlay() }, 500L)\n    }'''

if old not in text:
    raise SystemExit("Could not find old dispatchMappedTap block")

text = text.replace(old, new, 1)
path.write_text(text, encoding="utf-8")
print("Applied safe screen magnifier tap fallback")
